# Generated by Django 4.0 on 2024-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='room_id',
        ),
        migrations.AddField(
            model_name='event',
            name='room_reservation_id',
            field=models.CharField(default='default_value', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
