# Generated by Django 4.0 on 2024-08-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0002_remove_event_room_id_event_room_reservation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='room_reservation_id',
            new_name='room_id',
        ),
    ]
