# Generated by Django 4.0 on 2024-08-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_provider', '0003_rename_room_reservation_id_event_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room_id',
            field=models.CharField(max_length=64),
        ),
    ]
