# Generated by Django 4.0 on 2024-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('period', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('booking_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('hotel_id', 'period', 'year', 'month', 'day')},
            },
        ),
    ]
