# Generated by Django 4.0 on 2024-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bookings_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('hotel_id', 'year', 'month', 'day')},
        ),
        migrations.CreateModel(
            name='ProcessedDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='booking_count',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='period',
        ),
    ]
